### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by jim-rosales** [benjaminfeit/prj-rev-bwfs-dasmoto#4]
Considering all your elements use the font Helvetica it is a bit more efficient to apply it in the following way:

```CSS
p,
span,
h1,
h2 {
  font-family: Helvetica, serif; /* It's a good idea to also provide a fallback font */
}
```

https://github.com/benjaminfeit/prj-rev-bwfs-dasmoto/blob/f9c65ef1477deaecbef87160ebbfb8da9161e39f/Dasmoto/resources/style.css#L2
